services:
    php74:
        image: ghcr.io/ibexa/docker/php:7.4-node18
        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
            - ~/.ssh:/var/www/.ssh
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - PHP_INI_ENV_error_reporting
            - APP_ENV=${APP_ENV-dev}
            - APP_DEBUG
            - APP_HTTP_CACHE
            - TRUSTED_PROXIES
            - DATABASE_PLATFORM
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - DATABASE_VERSION
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - XDEBUG_CONFIG
            - COMPOSER_HOME=~/.composer
        networks:
            - backend

    php80:
        image: ghcr.io/ibexa/docker/php:8.0-node18
        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
            - ~/.ssh:/var/www/.ssh
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - PHP_INI_ENV_error_reporting
            - APP_ENV=${APP_ENV-dev}
            - APP_DEBUG
            - APP_HTTP_CACHE
            - TRUSTED_PROXIES
            - DATABASE_PLATFORM
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - DATABASE_VERSION
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - XDEBUG_CONFIG
            - COMPOSER_HOME=~/.composer
        networks:
            - backend

    php81:
        image: ghcr.io/ibexa/docker/php:8.1-node18
        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
            - ~/.ssh:/var/www/.ssh
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - PHP_INI_ENV_error_reporting
            - APP_ENV=${APP_ENV-dev}
            - APP_DEBUG
            - APP_HTTP_CACHE
            - TRUSTED_PROXIES
            - DATABASE_PLATFORM
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - DATABASE_VERSION
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - XDEBUG_CONFIG
            - COMPOSER_HOME=~/.composer
        networks:
            - backend

    php82:
        image: ghcr.io/ibexa/docker/php:8.2-node18
        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
            - ~/.ssh:/var/www/.ssh
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - PHP_INI_ENV_error_reporting
            - APP_ENV=${APP_ENV-dev}
            - APP_DEBUG
            - APP_HTTP_CACHE
            - TRUSTED_PROXIES
            - DATABASE_PLATFORM
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - DATABASE_VERSION
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - XDEBUG_CONFIG
            - COMPOSER_HOME=~/.composer
        networks:
            - backend

    php83:
        image: ghcr.io/ibexa/docker/php:8.3-node18
        volumes:
            - ${COMPOSE_DIR}/../../:/var/www:cached
            - ${COMPOSER_HOME}:/root/.composer:cached
            - ~/.ssh:/var/www/.ssh
        depends_on:
            - db
        environment:
            - COMPOSER_MEMORY_LIMIT
            - ENABLE_XDEBUG
            - EZPLATFORM_SITEACCESS
            - PHP_INI_ENV_memory_limit
            - PHP_INI_ENV_error_reporting
            - APP_ENV=${APP_ENV-dev}
            - APP_DEBUG
            - APP_HTTP_CACHE
            - TRUSTED_PROXIES
            - DATABASE_PLATFORM
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_NAME
            - DATABASE_HOST=db
            - DATABASE_VERSION
            - RECOMMENDATIONS_CUSTOMER_ID
            - RECOMMENDATIONS_LICENSE_KEY
            - PUBLIC_SERVER_URI
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
            - XDEBUG_CONFIG
            - COMPOSER_HOME=~/.composer
        networks:
            - backend
