FROM solr:6-alpine

# Copy solr config from the version used by eZ Platform
# fix : solr config seems no longer to be stored in vendor/ibexa
COPY vendor/ibexa/solr/src/lib/Resources/config/solr/ /opt/solr/server/tmp
#COPY vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/ /opt/solr/server/tmp

# commerce fix - start
COPY vendor/ibexa/commerce-shop/src/bundle/Search/Resources/config/solr/ /tmp/
#COPY vendor/ezsystems/ezcommerce-shop/src/Siso/Bundle/SearchBundle/Resources/config/solr/ /tmp/


USER root
RUN cat /tmp/custom-fields-types.xml >> /opt/solr/server/tmp/custom-fields-types.xml \
 && cat /tmp/language-fieldtypes.xml >> /opt/solr/server/tmp/language-fieldtypes.xml
USER $SOLR_USER

# commerce fix - end

# Prepare config
RUN mkdir -p /opt/solr/server/ez/template \
 && cp -R /opt/solr/server/tmp/* /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/currency.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/solrconfig.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/stopwords.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/synonyms.txt /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/configsets/basic_configs/conf/elevate.xml /opt/solr/server/ez/template \
 && cp /opt/solr/server/solr/solr.xml /opt/solr/server/ez \
 && sed -i.bak '/<updateRequestProcessorChain name="add-unknown-fields-to-the-schema">/,/<\/updateRequestProcessorChain>/d' /opt/solr/server/ez/template/solrconfig.xml \
 && sed -ie 's/${solr.autoSoftCommit.maxTime:-1}/${solr.autoSoftCommit.maxTime:20}/' /opt/solr/server/ez/template/solrconfig.xml

# Set our core config as home
ENV SOLR_HOME /opt/solr/server/ez

# Make sure core is created on startup
CMD ["solr-create", "-c", "collection1", "-d", "/opt/solr/server/ez/template"]
