version: '3.3'

services:
    app:
        environment:
         - SEARCH_ENGINE=elasticsearch
         - ELASTICSEARCH_DSN=http://elasticsearch:9200

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        environment:
         - discovery.type=single-node
        ports:
         - "9200:9200"
         - "9300:9300"
        networks:
         - backend
