version: '3.3'
# Config for having sessions in separate redis instance, to be appended after base-prod or base-dev, ..., but before selenium.yml

## WARNING:
# This service is currently work in progress, is not tested by CI, and thus not guaranteed to work.
# You are however more then welcome to try it out and help make it stable.

# IMPORTANT
# Requires you to define the following service:
#    app.session.handler.native_memcached:
#        class: Ibexa\Bundle\Core\Session\Handler\NativeSessionHandler
#        arguments:
#            - '%session.save_path%'
#            - memcached

services:
  app:
    depends_on:
     - memcached-session
    environment:
     - SESSION_HANDLER_ID=app.session.handler.native_memcached
     - SESSION_SAVE_PATH=memcached-session:11211

  memcached-session:
    image: memcached:1.6
    networks:
     - backend
