#!/bin/bash

# Export variables
export SENDMAIL_RELAY_HOST=${SENDMAIL_RELAY_HOST:-}
export SENDMAIL_RELAY_PORT=${SENDMAIL_RELAY_PORT:-25}
export SENDMAIL_RELAY_USER=${SENDMAIL_RELAY_USER:-}
export SENDMAIL_RELAY_PASSWORD=${SENDMAIL_RELAY_PASSWORD:-}
export SENDMAIL_RELAY_TLS_SECURITY_LEVEL=${SENDMAIL_RELAY_TLS_SECURITY_LEVEL:-may}
export WEB_HOST=${WEB_HOST:-domain.foo}
